### ISSUE TITLE
Milestones

### ISSUE THREAD

**Issue by vaheminasyan2** [vaheminasyan2/podhub#5]
- [ ] March 16 -- Plan, Design, and Research
- [ ] March 23 -- Ready MVP (Working App!), Mini-Presentation
- [ ] March 30 -- Project Polish, Functionality Push, Final Plan
- [ ] April 6 -- Presentation Time!
